### Series

In [1]:
import pandas as pd
import numpy as np
from datetime import date

In [8]:
a = np.arange(0,30,2)
np.random.shuffle(a)
a = a[0:5]

In [9]:
b = pd.Series(a)
b

0    20
1    24
2     8
3    26
4    18
dtype: int32

In [10]:
b.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
ind = [date(y,m,d) for y,m,d in [(2018, 1, 15), (2018, 4,19), (2018,3,24),(2018,7,8),(2018,10,10)]]
b = pd.Series(a, index=ind)
b

2018-01-15    20
2018-04-19    24
2018-03-24     8
2018-07-08    26
2018-10-10    18
dtype: int32

In [12]:
b.index

Index([2018-01-15, 2018-04-19, 2018-03-24, 2018-07-08, 2018-10-10], dtype='object')

In [13]:
b.index = pd.to_datetime(b.index, format = '%Y-%m-%d')

In [15]:
b.index, b.index.day

(DatetimeIndex(['2018-01-15', '2018-04-19', '2018-03-24', '2018-07-08',
                '2018-10-10'],
               dtype='datetime64[ns]', freq=None),
 Int64Index([15, 19, 24, 8, 10], dtype='int64'))

In [16]:
b = pd.Series(a, dtype = np.float64)

In [17]:
b

0    20.0
1    24.0
2     8.0
3    26.0
4    18.0
dtype: float64

In [18]:
b = pd.Series(a)
b = b.astype(np.float64)
b

0    20.0
1    24.0
2     8.0
3    26.0
4    18.0
dtype: float64

In [19]:
b.values

array([20., 24.,  8., 26., 18.])

In [20]:
b[[0,2]]

0    20.0
2     8.0
dtype: float64

In [21]:
b.head(2)

0    20.0
1    24.0
dtype: float64

In [22]:
b.tail(3)

2     8.0
3    26.0
4    18.0
dtype: float64

In [24]:
b[b > 25]

3    26.0
dtype: float64

In [25]:
b[(b == 20) | (b < 18)]

0    20.0
2     8.0
dtype: float64

In [45]:
b[(b > 5) & (b < 9)]

0    8.0
3    6.0
dtype: float64

In [29]:
b[b > 20] = 0
b

0    20
1     0
2     8
3     0
4    18
dtype: int32

In [30]:
b = pd.Series(a)
b

0    20
1     0
2     8
3     0
4    18
dtype: int32

In [32]:
b[[0,3,2]] = 1

In [33]:
b

0     1
1     0
2     1
3     1
4    18
dtype: int32

In [34]:
b = b.append(pd.Series(a[0:5]))

In [37]:
b

0     1
1     0
2     1
3     1
4    18
0     1
1     0
2     1
3     1
4    18
dtype: int32

In [38]:
b.head(2)

0    1
1    0
dtype: int32

In [39]:
b.tail(3)

2     1
3     1
4    18
dtype: int32

In [43]:
b.count()
b

0     1
1     0
2     1
3     1
4    18
0     1
1     0
2     1
3     1
4    18
dtype: int32

In [44]:
b.drop([3,4])

0    1
1    0
2    1
0    1
1    0
2    1
dtype: int32

In [46]:
b.to_pickle('b.pkl')
c = pd.read_pickle('b.pkl')
c

0     1
1     0
2     1
3     1
4    18
0     1
1     0
2     1
3     1
4    18
dtype: int32

### DataFrame

In [47]:
df = pd.DataFrame({'Col1':['a','b','c','d','e','f','g','h'],
                   'Col2':[1,2,3,4,5,6,7,8]}, columns=['Col1','Col2'])
df

Col1  Col2
0    a     1
1    b     2
2    c     3
3    d     4
4    e     5
5    f     6
6    g     7
7    h     8

In [48]:
df.shape

(8, 2)

In [49]:
df.columns

Index(['Col1', 'Col2'], dtype='object')

In [50]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Col1    8 non-null      object
 1   Col2    8 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 256.0+ bytes


In [52]:
df.describe()

Col2
count  8.00000
mean   4.50000
std    2.44949
min    1.00000
25%    2.75000
50%    4.50000
75%    6.25000
max    8.00000

In [53]:
df.head()

Col1  Col2
0    a     1
1    b     2
2    c     3
3    d     4
4    e     5

In [54]:
df.head(2)

Col1  Col2
0    a     1
1    b     2

In [55]:
df['Col1'].head(2)

0    a
1    b
Name: Col1, dtype: object

In [56]:
df.Col1.tail(2)

6    g
7    h
Name: Col1, dtype: object

In [57]:
df.index = [np.arange(2,17,2)]

In [64]:
df

Col1  Col2
2     a     1
4     b     2
6     c     3
8     d     4
10    e     5
12    f     6
14    g     7
16    h     8

In [58]:
df.loc[2, 'Col1']

2    a
Name: Col1, dtype: object

In [59]:
df.loc[2]

Col1  Col2
2    a     1

In [67]:
df.loc[1:7, :]

Col1  Col2
2    a     1
4    b     2
6    c     3

In [68]:
df.iloc[0]

Col1    a
Col2    1
Name: (2,), dtype: object

In [69]:
df.iloc[0:3]

Col1  Col2
2    a     1
4    b     2
6    c     3

In [70]:
df.loc[df['Col1'] == 'b']

Col1  Col2
4    b     2

In [71]:
df.loc[df['Col1'] == 'b'].values

array([['b', 2]], dtype=object)

In [72]:
df.loc[df.Col2.between(3,6)]

Col1  Col2
6     c     3
8     d     4
10    e     5
12    f     6

In [73]:
df.loc[~df.Col2.isin(np.arange(0,5))]

Col1  Col2
10    e     5
12    f     6
14    g     7
16    h     8

In [74]:
df.query('Col1 == "b"')

Col1  Col2
4    b     2

In [75]:
df.query('Col2 > 5')

Col1  Col2
12    f     6
14    g     7
16    h     8

In [76]:
s = df['Col1']
s

2     a
4     b
6     c
8     d
10    e
12    f
14    g
16    h
Name: Col1, dtype: object

In [77]:
type(s)

pandas.core.series.Series

In [78]:
df.sample(n=3)

Col1  Col2
6     c     3
10    e     5
2     a     1

In [79]:
df.sample(frac=0.3)

Col1  Col2
6    c     3
2    a     1

In [82]:
df.sample(frac=0.7,replace=True)

Col1  Col2
6     c     3
8     d     4
12    f     6
12    f     6
8     d     4
12    f     6

In [83]:
df.sample(frac = 1.0, random_state=42)

Col1  Col2
4     b     2
12    f     6
2     a     1
16    h     8
6     c     3
10    e     5
8     d     4
14    g     7

In [84]:
df.to_csv('Test.csv', sep = ';')

In [85]:
df_new = pd.read_csv('Test.csv', sep = ';', index_col=0)

In [86]:
df_new

Col1  Col2
2     a     1
4     b     2
6     c     3
8     d     4
10    e     5
12    f     6
14    g     7
16    h     8

### Работа с DF

In [87]:
authors = pd.DataFrame({'author_id': [1,2,3],
                        'author_name':['Pushkin', 'Tolstoy', 'Dostoevski']},
                       columns=['author_id','author_name'])
authors

author_id author_name
0          1     Pushkin
1          2     Tolstoy
2          3  Dostoevski

In [88]:
books = pd.DataFrame({'author_id': [2,3,3,4],
                      'book_title':['War and Peace', 'The Idiot', 'Crime and Punishment', 'Fathers and Sons']})

In [89]:
books

author_id            book_title
0          2         War and Peace
1          3             The Idiot
2          3  Crime and Punishment
3          4      Fathers and Sons

In [90]:
df2 = pd.merge(authors,books,on='author_id', how='left')
df2

author_id author_name            book_title
0          1     Pushkin                   NaN
1          2     Tolstoy         War and Peace
2          3  Dostoevski             The Idiot
3          3  Dostoevski  Crime and Punishment

In [91]:
df3 = pd.merge(authors,books,on='author_id', how='right')
df3

author_id author_name            book_title
0          2     Tolstoy         War and Peace
1          3  Dostoevski             The Idiot
2          3  Dostoevski  Crime and Punishment
3          4         NaN      Fathers and Sons

In [92]:
df1 = pd.merge(authors,books,on='author_id', how='inner')
df1

author_id author_name            book_title
0          2     Tolstoy         War and Peace
1          3  Dostoevski             The Idiot
2          3  Dostoevski  Crime and Punishment

In [93]:
df4 = pd.merge(authors,books,on='author_id', how='outer')

In [94]:
df4.loc[df4.book_title.isnull()]

author_id author_name book_title
0          1     Pushkin        NaN

In [95]:
df4.loc[df4.author_name.notnull()]

author_id author_name            book_title
0          1     Pushkin                   NaN
1          2     Tolstoy         War and Peace
2          3  Dostoevski             The Idiot
3          3  Dostoevski  Crime and Punishment

In [96]:
df4.book_title=df4.book_title.fillna('unknown');
df4

author_id author_name            book_title
0          1     Pushkin               unknown
1          2     Tolstoy         War and Peace
2          3  Dostoevski             The Idiot
3          3  Dostoevski  Crime and Punishment
4          4         NaN      Fathers and Sons

In [97]:
df4.author_name = df4.author_name.fillna('unknown')
df4

author_id author_name            book_title
0          1     Pushkin               unknown
1          2     Tolstoy         War and Peace
2          3  Dostoevski             The Idiot
3          3  Dostoevski  Crime and Punishment
4          4     unknown      Fathers and Sons

In [98]:
df4.loc[(df4.author_name != 'unknown') & (df4.book_title != 'unknown'), 'quantity'] = 1
df4

author_id author_name            book_title  quantity
0          1     Pushkin               unknown       NaN
1          2     Tolstoy         War and Peace       1.0
2          3  Dostoevski             The Idiot       1.0
3          3  Dostoevski  Crime and Punishment       1.0
4          4     unknown      Fathers and Sons       NaN

In [99]:
df4.quantity.fillna(0, inplace = True)

In [100]:
df4

author_id author_name            book_title  quantity
0          1     Pushkin               unknown       0.0
1          2     Tolstoy         War and Peace       1.0
2          3  Dostoevski             The Idiot       1.0
3          3  Dostoevski  Crime and Punishment       1.0
4          4     unknown      Fathers and Sons       0.0

In [101]:
df4.quantity = df4.quantity.astype(int)
df4

author_id author_name            book_title  quantity
0          1     Pushkin               unknown         0
1          2     Tolstoy         War and Peace         1
2          3  Dostoevski             The Idiot         1
3          3  Dostoevski  Crime and Punishment         1
4          4     unknown      Fathers and Sons         0

In [102]:
df4.set_index('author_id', inplace = True)

In [103]:
df4

author_name            book_title  quantity
author_id                                            
1             Pushkin               unknown         0
2             Tolstoy         War and Peace         1
3          Dostoevski             The Idiot         1
3          Dostoevski  Crime and Punishment         1
4             unknown      Fathers and Sons         0

In [104]:
df4.reset_index(inplace = True)

In [105]:
df4

author_id author_name            book_title  quantity
0          1     Pushkin               unknown         0
1          2     Tolstoy         War and Peace         1
2          3  Dostoevski             The Idiot         1
3          3  Dostoevski  Crime and Punishment         1
4          4     unknown      Fathers and Sons         0

In [106]:
df['price'] = 500
df

Col1  Col2  price
2     a     1    500
4     b     2    500
6     c     3    500
8     d     4    500
10    e     5    500
12    f     6    500
14    g     7    500
16    h     8    500

In [107]:
df.drop('price', axis=1)

Col1  Col2
2     a     1
4     b     2
6     c     3
8     d     4
10    e     5
12    f     6
14    g     7
16    h     8

In [108]:
df['price'] = 500
df

Col1  Col2  price
2     a     1    500
4     b     2    500
6     c     3    500
8     d     4    500
10    e     5    500
12    f     6    500
14    g     7    500
16    h     8    500

In [109]:
df.drop(2, axis=0)

Col1  Col2  price
4     b     2    500
6     c     3    500
8     d     4    500
10    e     5    500
12    f     6    500
14    g     7    500
16    h     8    500

In [110]:
df4.sort_values(by='author_id')

author_id author_name            book_title  quantity
0          1     Pushkin               unknown         0
1          2     Tolstoy         War and Peace         1
2          3  Dostoevski             The Idiot         1
3          3  Dostoevski  Crime and Punishment         1
4          4     unknown      Fathers and Sons         0

In [111]:
df4 = df4.reset_index(drop=True)

In [112]:
df4

author_id author_name            book_title  quantity
0          1     Pushkin               unknown         0
1          2     Tolstoy         War and Peace         1
2          3  Dostoevski             The Idiot         1
3          3  Dostoevski  Crime and Punishment         1
4          4     unknown      Fathers and Sons         0

In [113]:
hh = np.linspace(200,800,5)
hh

array([200., 350., 500., 650., 800.])

In [114]:
np.random.shuffle(hh)
hh

array([350., 200., 800., 500., 650.])

In [115]:
df4['price'] = hh
df4

author_id author_name            book_title  quantity  price
0          1     Pushkin               unknown         0  350.0
1          2     Tolstoy         War and Peace         1  200.0
2          3  Dostoevski             The Idiot         1  800.0
3          3  Dostoevski  Crime and Punishment         1  500.0
4          4     unknown      Fathers and Sons         0  650.0

In [117]:
df4['total'] = df4.quantity * df4.price
df4

author_id author_name            book_title  quantity  price  total
0          1     Pushkin               unknown         0  350.0    0.0
1          2     Tolstoy         War and Peace         1  200.0  200.0
2          3  Dostoevski             The Idiot         1  800.0  800.0
3          3  Dostoevski  Crime and Punishment         1  500.0  500.0
4          4     unknown      Fathers and Sons         0  650.0    0.0

In [118]:
df4['price'].max()

800.0

In [119]:
df4['price'].min()

200.0

In [120]:
df4['price'].mean()

500.0

In [121]:
df4['price'].median()

500.0

In [122]:
df4['price'].std()

237.17082451262846

In [123]:
df4['price'].var()

56250.0

In [124]:
df4.nlargest(2, 'price')

author_id author_name        book_title  quantity  price  total
2          3  Dostoevski         The Idiot         1  800.0  800.0
4          4     unknown  Fathers and Sons         0  650.0    0.0

In [125]:
df4.author_name.unique()

array(['Pushkin', 'Tolstoy', 'Dostoevski', 'unknown'], dtype=object)

In [126]:
df4.author_name.nunique()

4

In [127]:
df4.author_name.value_counts()

Dostoevski    2
Tolstoy       1
unknown       1
Pushkin       1
Name: author_name, dtype: int64

In [128]:
df4.groupby('author_name')['price'].max()

author_name
Dostoevski    800.0
Pushkin       350.0
Tolstoy       200.0
unknown       650.0
Name: price, dtype: float64

In [129]:
price_agg = df4.groupby('author_name').agg({'price': 'max'})
price_agg

price
author_name       
Dostoevski   800.0
Pushkin      350.0
Tolstoy      200.0
unknown      650.0

In [130]:
price_agg = price_agg.rename(columns={'price':'max_price'})
price_agg

max_price
author_name           
Dostoevski       800.0
Pushkin          350.0
Tolstoy          200.0
unknown          650.0