In [1]:
import numpy as np

In [2]:
a = [i for i in range(12)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [4]:
b = np.array(a)

In [5]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
b = np.array([i for i in range(10)])

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(b)

numpy.ndarray

In [9]:
b = np.array(a, dtype = float)

In [10]:
b.dtype

dtype('float64')

In [11]:
b[0]

0.0

In [12]:
b.ndim

1

In [13]:
b.shape

(12,)

In [14]:
b = np.array([[i for i in range(10)] for j in range(10)], float)
b

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [15]:
b.size

100

In [16]:
b[2,3]

3.0

In [17]:
b[:2, 3:]

array([[3., 4., 5., 6., 7., 8., 9.],
       [3., 4., 5., 6., 7., 8., 9.]])

In [18]:
c = b[:2, 3:]
b[1,4]=28
c

array([[ 3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 3., 28.,  5.,  6.,  7.,  8.,  9.]])

In [19]:
c = b[:2, 4:].copy()
b[1,4] = 55
c, b[:2, 4:]

(array([[ 4.,  5.,  6.,  7.,  8.,  9.],
        [28.,  5.,  6.,  7.,  8.,  9.]]),
 array([[ 4.,  5.,  6.,  7.,  8.,  9.],
        [55.,  5.,  6.,  7.,  8.,  9.]]))

In [21]:
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3., 55.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [22]:
c

array([[ 4.,  5.,  6.,  7.,  8.,  9.],
       [28.,  5.,  6.,  7.,  8.,  9.]])

### Data types

In [23]:
b = np.array(a, dtype = np.float32)

In [24]:
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)

In [25]:
b = np.array(a, dtype = np.float64)

In [26]:
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])