In [11]:
import numpy as np

In [13]:
a = [i for i in range(10)]

In [14]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
b = np.array(a)

In [16]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b = np.array([i for i in range(10)])

In [18]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
type(b)

numpy.ndarray

In [20]:
b = np.array(a, dtype = float)

In [22]:
b.dtype

dtype('float64')

In [24]:
b[0]

0.0

In [26]:
b.ndim

1

In [27]:
b.shape

(10,)

In [32]:
b = np.array([[i for i in range(10)] for j in range(10)], float)
b

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
b.size

100

In [35]:
b[2,3]

3.0

In [38]:
b[:2, 3:]

array([[3., 4., 5., 6., 7., 8., 9.],
       [3., 4., 5., 6., 7., 8., 9.]])

In [41]:
c = b[:2, 3:]
b[1,4]=28
c

array([[ 3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 3., 28.,  5.,  6.,  7.,  8.,  9.]])

In [47]:
c = b[:2, 4:].copy()
b[1,4] = 55
c, b[:2, 4:]

(array([[ 4.,  5.,  6.,  7.,  8.,  9.],
        [42.,  5.,  6.,  7.,  8.,  9.]]),
 array([[ 4.,  5.,  6.,  7.,  8.,  9.],
        [55.,  5.,  6.,  7.,  8.,  9.]]))