In [5]:
import numpy as np

### Автоматическое создание массивов

In [6]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [12]:
np.arange(10, 0, -0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5])

Тут 3-ий аргумент, вместо шага количество элементов

In [13]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

1 и 2 аргументы - это степени числа 10, соответственно, в примере ниже, берем 20 элементов от 10^1 до 10^3

In [14]:
np.logspace(1,3,20)

array([  10.        ,   12.74274986,   16.23776739,   20.69138081,
         26.36650899,   33.59818286,   42.81332399,   54.55594781,
         69.51927962,   88.58667904,  112.88378917,  143.84498883,
        183.29807108,  233.57214691,  297.63514416,  379.26901907,
        483.29302386,  615.84821107,  784.75997035, 1000.        ])

### Генерация чисел

In [15]:
np.random.sample()

0.7880717489059018

In [16]:
np.random.sample((2,3))

array([[0.49586674, 0.50557355, 0.10251794],
       [0.03527407, 0.27509247, 0.83624844]])

In [17]:
np.random.sample((48, 64, 3))

array([[[0.4249165 , 0.68493451, 0.36928027],
        [0.53908935, 0.26613819, 0.26387303],
        [0.37180195, 0.49194102, 0.9208682 ],
        ...,
        [0.16060159, 0.57255901, 0.29931093],
        [0.20828422, 0.42373372, 0.68475992],
        [0.34710841, 0.09800936, 0.36796131]],

       [[0.5274331 , 0.19660063, 0.32328414],
        [0.3847353 , 0.81413596, 0.93230504],
        [0.05750636, 0.57868432, 0.28015659],
        ...,
        [0.17704023, 0.51598247, 0.93268439],
        [0.47464013, 0.25708028, 0.32535189],
        [0.83942325, 0.6620345 , 0.83553546]],

       [[0.97983533, 0.96132162, 0.89916408],
        [0.84458213, 0.93162803, 0.70818513],
        [0.72472983, 0.71607079, 0.61171816],
        ...,
        [0.35525378, 0.12938697, 0.29493137],
        [0.5659676 , 0.63697274, 0.20511297],
        [0.41022125, 0.91771691, 0.70631928]],

       ...,

       [[0.9603028 , 0.94372182, 0.83942662],
        [0.20337589, 0.9467859 , 0.84211028],
        [0.70400226, 0

Тут мы генерим случайные числа с нормальным распределением (среднее значение 0, среднеквадратичное отклонение 1)

In [18]:
np.random.randn(10)

array([ 1.7027456 , -0.10172315,  1.5532501 , -0.9423115 , -0.52712231,
       -1.16418722,  1.0735086 ,  1.35499177, -1.2168506 ,  0.42614347])

Случаные интовые числа от 0 до 100

In [19]:
A = np.random.randint(0, 100, (3,4))
A

array([[93, 33, 60, 80],
       [53, 65, 78, 57],
       [99, 76, 48, 93]])

In [20]:
B = A.flatten()
B

array([93, 33, 60, 80, 53, 65, 78, 57, 99, 76, 48, 93])

Случайны числа из другого массива

In [21]:
np.random.choice(B, (2,4))

array([[60, 53, 57, 93],
       [76, 65, 65, 93]])

np.random.seed - инициализация генератора случайных чисел

In [22]:
a = np.arange(12)

In [23]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
a.resize(3,4)

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a = a.flatten()

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Соединение массивов

In [30]:
a = np.random.randint(0,100,(2,3))
a

array([[40, 93, 90],
       [89,  9, 73]])

In [31]:
b = np.random.randint(0,100,(2,3))
b

array([[57, 67, 14],
       [95, 34, 12]])

In [32]:
v = np.vstack((a,b))
v

array([[40, 93, 90],
       [89,  9, 73],
       [57, 67, 14],
       [95, 34, 12]])

In [33]:
v = np.concatenate((a,b), axis = 0)
v

array([[40, 93, 90],
       [89,  9, 73],
       [57, 67, 14],
       [95, 34, 12]])

In [34]:
h = np.hstack((a,b))
h

array([[40, 93, 90, 57, 67, 14],
       [89,  9, 73, 95, 34, 12]])

In [35]:
h = np.concatenate((a,b), axis = 1)
h

array([[40, 93, 90, 57, 67, 14],
       [89,  9, 73, 95, 34, 12]])

In [36]:
d = np.dstack((a,b))

In [37]:
d

array([[[40, 57],
        [93, 67],
        [90, 14]],

       [[89, 95],
        [ 9, 34],
        [73, 12]]])

In [38]:
d

array([[[40, 57],
        [93, 67],
        [90, 14]],

       [[89, 95],
        [ 9, 34],
        [73, 12]]])