In [1]:
import numpy as np

In [5]:
a = np.array([i for i in range(5)])
b = np.array([i for i in range(5,10)])
a,b

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [6]:
c = a + b
c

array([ 5,  7,  9, 11, 13])

In [8]:
al = [i for i in range(5)]
bl = [i for i in range(5,10)]
al + bl

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
c = np.add(al, bl)
c

array([ 5,  7,  9, 11, 13])

In [13]:
a = np.array([i for i in range(0,15,3)])
b = np.array([i for i in range(1,11,2)])
a,b

(array([ 0,  3,  6,  9, 12]), array([1, 3, 5, 7, 9]))

In [15]:
d = a - b
d

array([-1,  0,  1,  2,  3])

In [17]:
a.shape == b.shape

True

### Умнажение векторов

In [18]:
a = np.array([i for i in range(5)])
c = a * 2
c

array([0, 2, 4, 6, 8])

In [19]:
c = a * -10
c

array([  0, -10, -20, -30, -40])

In [21]:
c = a * 0.5
c

array([0. , 0.5, 1. , 1.5, 2. ])

### Алтернативные способы умножения вектора на скаляр

In [22]:
a.dot(5)

array([ 0,  5, 10, 15, 20])

In [23]:
np.dot(3,a)

array([ 0,  3,  6,  9, 12])

### Скалярное произведение векторов

In [27]:
a = np.array([1,3,5])
b = np.array([2,5,8])
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

57

In [28]:
a @ b

57

In [29]:
a.dot(b)

57

### Операции с матрицами

In [36]:
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[6,7],[8,9],[10,11]])
print('{}\n{}'.format(A,B))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [37]:
A.shape

(3, 2)

### Сложение матриц

Измерения матриц должны совпадать

In [38]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [39]:
C = np.add(A,B)

### Вычитание

Размерность должна быть одинаковой

In [40]:
D = A - B
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [43]:
D = np.subtract(A,B)
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

### Умножение матрицы на скаляр

In [44]:
X = A * 2
X

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [46]:
X = np.dot(A,2)
X

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])