### Операции с векторами

Сложение и вычитание. Возможно только если размерности векторов равны (параметр shape). Сложение и вычитание векторов - это поэлементное сложение или вычитание их элементов.

In [1]:
import numpy as np

In [6]:
a = np.array([i for i in range(5)])
b = np.array([i for i in range(5,10)])
print(a, b)
print(a.size, b.size)
print(a.shape, b.shape)

[0 1 2 3 4] [5 6 7 8 9]
5 5
(5,) (5,)


In [7]:
c = a + b
c

array([ 5,  7,  9, 11, 13])

In [8]:
al = [i for i in range(5)]
bl = [i for i in range(5,10)]
al + bl

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### *Альтернативный способ сложения (можно слкадывать списки)*

In [9]:
c = np.add(al, bl)
c

array([ 5,  7,  9, 11, 13])

#### *Вычитание векторов*

In [10]:
a = np.array([i for i in range(0,15,3)])
b = np.array([i for i in range(1,11,2)])
a,b

(array([ 0,  3,  6,  9, 12]), array([1, 3, 5, 7, 9]))

In [11]:
d = a - b
d

array([-1,  0,  1,  2,  3])

In [12]:
a.shape == b.shape

True

#### *Альтернативный способ*

In [14]:
d = np.subtract(a, b)
d

array([-1,  0,  1,  2,  3])

### Умножение вектора на скаляр

In [15]:
a = np.array([i for i in range(5)])
c = a * 2
c

array([0, 2, 4, 6, 8])

In [16]:
c = a * -10
c

array([  0, -10, -20, -30, -40])

In [17]:
c = a * 0.5
c

array([0. , 0.5, 1. , 1.5, 2. ])

#### *Алтернативные способы умножения вектора на скаляр*

In [18]:
a.dot(5)

array([ 0,  5, 10, 15, 20])

In [19]:
np.dot(3,a)

array([ 0,  3,  6,  9, 12])

### Скалярное произведение векторов

In [20]:
a = np.array([1,3,5])
b = np.array([2,5,8])
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

57

In [21]:
a @ b

57

In [22]:
a.dot(b)

57

### Операции с матрицами

In [23]:
A = np.array([[0,1],
              [2,3],
              [4,5]])
B = np.array([[6,7],
              [8,9],
              [10,11]])
print('{}\n{}'.format(A,B))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [24]:
A.shape

(3, 2)

### Сложение матриц

Измерения матриц должны совпадать

In [25]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [30]:
C = np.add(A,B)
print('{}\n+\n{}\n=\n{}'.format(A,B,C))

[[0 1]
 [2 3]
 [4 5]]
+
[[ 6  7]
 [ 8  9]
 [10 11]]
=
[[ 6  8]
 [10 12]
 [14 16]]


### Вычитание

Размерность должна быть одинаковой

In [31]:
D = A - B
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [32]:
D = np.subtract(A,B)
print('{}\n-\n{}\n=\n{}'.format(A,B,D))

[[0 1]
 [2 3]
 [4 5]]
-
[[ 6  7]
 [ 8  9]
 [10 11]]
=
[[-6 -6]
 [-6 -6]
 [-6 -6]]


### Умножение матрицы на скаляр

In [34]:
X = A * 2
print('{}\n*\n {}\n=\n{}'.format(A,2,X))

[[0 1]
 [2 3]
 [4 5]]
*
 2
=
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [35]:
X = np.dot(A,2)
X

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])