In [ ]:
import numpy as np

In [ ]:
a = np.arange(12,24)

In [53]:
def randomize2DShapeArray(shapeQuntifier):
    for i in range(0, a.shape[0]):
        if i < 2:
            continue
        elif a.shape[0] % i == 0:
            first_dim_array.append(i)
    first_dim = np.random.choice(first_dim_array)
    second_dim = a.shape[0] // first_dim
    return np.reshape(np.random.choice(a, 12, False), (first_dim, second_dim))
    

In [56]:
result = [randomize2DShapeArray(a.shape[0]) for i in range(0, 5)]
result

[array([[19, 23, 16, 14],
        [15, 12, 13, 20],
        [18, 22, 17, 21]]),
 array([[12, 14],
        [15, 23],
        [22, 17],
        [16, 20],
        [21, 19],
        [13, 18]]),
 array([[16, 15],
        [14, 18],
        [22, 19],
        [23, 20],
        [12, 17],
        [21, 13]]),
 array([[15, 21, 18, 17, 23, 14],
        [16, 13, 12, 22, 20, 19]]),
 array([[21, 23, 20, 15, 12, 14],
        [13, 19, 22, 16, 18, 17]])]

In [ ]:
12 % 3